---
title: "STAT2003 - Assignment 2"
author: "Amanda Efendi & Nina Kumagai"
date: "13/10/2019"
output: word_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Stationary Case
```{r}
stationary = read.csv("stationary.csv", header = TRUE, row.names = 1)
head(stationary)
```

```{r}
stationary$phi = as.factor(stationary$phi)
stationary$theta = as.factor(stationary$theta)
str(stationary)
```

```{r} 
st_anova = aov((1/MAPE) ~ phi*theta*Method, data = stationary)
summary(st_anova)
```

```{r}
#step(st_anova)
```

```{r}
library(FrF2)
MEPlot(st_anova)
```

```{r}
plot(st_anova)
```

```{r}
shapiro.test(st_anova$residuals)
```

```{r}
library(car)
leveneTest(st_anova)
```

```{r}
# HOW TO MAKE 3D INTERACTION PLOT
#par(pty='s')
#interaction.plot(stationary$theta, stationary$Method, stationary$MAPE, stationary$phi, xlab='Theta', ylab='MAPE', main='Non-Stationary - Interaction')
```



# Non-Stationary Case
```{r}
nonstationary = read.csv("non-stationary.csv", header = TRUE, row.names = 1)
head(nonstationary)
```

```{r}
nonstationary$theta = as.factor(nonstationary$theta)
str(nonstationary)
```

```{r}
non_st_anova = aov((1/MAPE) ~ theta*Method, data=nonstationary)
```

```{r}
summary(non_st_anova)
```

```{r}
step(non_st_anova)
```

```{r}
library(FrF2)
#MEPlot(non_st_anova)
```

```{r}
shapiro.test(non_st_anova$residuals)
```

```{r}
library(car)
leveneTest(non_st_anova)
```

```{r}
par(pty='s')
interaction.plot(nonstationary$theta, nonstationary$Method, nonstationary$MAPE, xlab='Theta', ylab='MAPE', main='Non-Stationary - Interaction')
```




# Question 2
# Simulating ARMA and IMA (ARIMA)

```{r message = FALSE}
library(mvtnorm)
library(e1071)
```

```{r}
#rho <- -0.9
##rho <- 0.9
#mu <- c(0.01,0.01)
#theta <- c(-0.9,0.9)
#d <- ts(matrix(0,ncol=2,nrow=1001))
#e <- ts(rmvnorm(1001,sigma=cbind(c(400,rho*400),c(rho*400,400))))
#for(i in 2:1001)
# d[i,] <- mu + d[i-1,] - theta*(e[i-1,]+e[i,])

#par(mfrow=c(1,2))
#plot(d[,1]);plot(d[,2])
```

## Stationary Process

```{r}
#Stationary process
#y <- arima.sim(n=100, model=list(ar=c(-0.9,0.9), ma=c(-0.9,0.9)), rand.gen=rnorm)]
set.seed(61)
arma.sim <- arima.sim(model=list(ar=-0.9,ma=-0.9),n=51)
arma.sim
ts.plot(arma.sim)
```

## simulating data

```{r}
#Simulate ARIMA based on the phi and theta parameter as function input
#Output the result as a 51x1 matrix with each row having 51 sequences of ts data

simData <- function(phi,theta){
  all_training=NULL
  for (i in 1:50){
    arimaSet = arima.sim(model=list(ar=phi, ma=theta),n=51)
    all_training = rbind(all_training, arimaSet[1:51])
  }
  return(all_training)
}
```

```{r}
#LLdata means low setting for both phi and theta
#LLdata has 50 rows and 51 columns
set.seed(61)
LLdata = simData(-0.9,-0.9)
LHdata = simData(-0.9,0.9)
```

## start SVM prediction using first row

```{r}
#training data is column 1 to 50
#test data is column 51st
#we only use the first row to test out.. not sure how to run all 50 rows..
trainSVMDat = data.frame(timestamp=c(seq(1,50,1)),value=LHdata[1,1:50])
testSVMDat = data.frame(timestamp=1,value=LHdata[1,51])
```

```{r}
#svm(y~x,data=training)
#the epsilon, gamma and cost values were taken from the paper
#the syntax we used is "to predict value using timestamp"
#predict(trainingmodel, newdata=testset)
LHmodelSVM = svm(value~timestamp,data=trainSVMDat,epsilon=0.1,gamma=0.1,cost=10)
LHpredSVM = predict(LHmodelSVM,newdata=testSVMDat); LHpredSVM
```

```{r}
#MAPE is the prediction - actual data squared divided by the number of rows put into SVM (?)
MAPE = ((LHpredSVM - testSVMDat[,2])^2)/1; MAPE
```

### start SVM prediction with SECOND row

```{r}
#using the second row from LHdata
#this is not the same setting as the first trial above (LL), this is (LH)
trainSVMDat = data.frame(timestamp=c(seq(1,50,1)),value=LHdata[2,1:50])
testSVMDat = data.frame(timestamp=1,value=LHdata[2,51])
```

```{r}
LHmodelSVM = svm(value~timestamp,data=trainSVMDat,epsilon=0.1,gamma=0.1,cost=10)
LHpredSVM = predict(LHmodelSVM,newdata=testSVMDat); LHpredSVM
```

```{r}
#MAPE is the prediction - actual data squared divided by the number of rows put into SVM (?)
MAPE = ((LHpredSVM - testSVMDat[,2])^2)/1; MAPE
```
